[phases.setup]
nixPkgs = ['nodejs']
nixOverlay = "https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"

[phases.install]
cmds = ['npm ci --production']

[phases.build]
cmds = ['echo "Build completed successfully"']

[start]
cmd = 'node server/server.js'