name: employee-management-system
services:
- name: web
  source_dir: /
  github:
    repo: your-username/employee-management-system
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: Dockerfile
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 3
    success_threshold: 1
  envs:
  - key: NODE_ENV
    value: "production"
  - key: JWT_SECRET
    type: SECRET
  - key: DB_ENCRYPTION_KEY
    type: SECRET
  - key: SESSION_SECRET
    type: SECRET
  - key: CORS_ORIGIN
    value: "https://your-domain.com"
  - key: TELEGRAM_BOT_TOKEN
    type: SECRET
    value: "process.env.TELEGRAM_BOT_TOKEN"
  - key: TELEGRAM_CHAT_ID
    value: "process.env.TELEGRAM_GROUP_ID"
    
databases:
- name: employee-db
  engine: MYSQL
  version: "8"
  size_slug: db-s-1vcpu-1gb
  
- name: employee-redis
  engine: REDIS
  version: "7"
  size_slug: db-s-1vcpu-1gb